# Generated by package_business_source.ps1. This file exists only in Business Source packages.
get_filename_component(_smrobot_business_source_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

if(NOT SMROBOT_PREBUILT_PACKAGE_ROOT)
    set(SMROBOT_PREBUILT_PACKAGE_ROOT "${_smrobot_business_source_root}/PrebuiltPackages" CACHE PATH
        "Business Source Common/Core/Platform prebuilt package root.")
endif()
if(NOT SMROBOT_PREBUILT_THIRDPARTY_ROOT)
    set(SMROBOT_PREBUILT_THIRDPARTY_ROOT "${_smrobot_business_source_root}/PrebuiltPackages/thirdparty" CACHE PATH
        "Business Source prebuilt third-party root.")
endif()
if(NOT SMROBOT_THIRDPARTY_ROOT)
    set(SMROBOT_THIRDPARTY_ROOT "${_smrobot_business_source_root}/PrebuiltPackages/thirdparty" CACHE PATH
        "Business Source third-party dependency root.")
endif()
if((NOT DEFINED PREBUILD_DIR OR PREBUILD_DIR STREQUAL "")
   AND DEFINED ENV{RS2026_EXTERNAL_PREBUILD_ROOT}
   AND NOT "$ENV{RS2026_EXTERNAL_PREBUILD_ROOT}" STREQUAL "")
    set(PREBUILD_DIR "$ENV{RS2026_EXTERNAL_PREBUILD_ROOT}" CACHE PATH
        "External Windows Qt/OMPL dependency root.")
endif()

# Common, Core and Platform are consumed from the exported SDK in a Business Source package.
set(UsingPrebuilt_Common ON CACHE BOOL "Use prebuilt Common package." FORCE)
set(UsingPrebuilt_SMRobotCore ON CACHE BOOL "Use prebuilt SMRobotCore package." FORCE)
set(UsingPrebuilt_SMRobotPlatform ON CACHE BOOL "Use prebuilt SMRobotPlatform package." FORCE)
set(RS2026_4090_ENABLE_DEMAND_LOADING ON CACHE BOOL
    "Load only dependencies required by the packaged Windows build graph." FORCE)

message(STATUS "Business Source defaults enabled; Common/Core/Platform will be loaded from ${SMROBOT_PREBUILT_PACKAGE_ROOT}.")
unset(_smrobot_business_source_root)